/***********************************************************************************
NAME: Apolinario Langa
PURPOSE: Answer business and metadata questions using the AdventureWorks database.

MODIFICATION LOG:
Ver     Date        Author              Description
-----   ----------  ------------------  -------------------------------------------
1.0     09/29/2026  Apolinario Langa    Built script for AdventureWorks assignment.

RUNTIME:
Less than 1 minute

NOTES:
This script contains SQL statements that answer business user and metadata
questions using the AdventureWorks sample database.
***********************************************************************************/

USE AdventureWorks2022;
GO

-- Q1 Author: Apolinario Langa
-- Q1: What are the 5 most expensive products by list price?
-- A1: Retrieve the five products with the highest list prices.

SELECT TOP 5
       ProductID,
       Name,
       ListPrice
FROM Production.Product
ORDER BY ListPrice DESC;
GO

-- Q2 Author: Apolinario Langa
-- Q2: Which five products have the highest list prices?
-- A2: Display the top five products ordered by list price.

SELECT TOP 5
       ProductID,
       Name,
       ListPrice
FROM Production.Product
ORDER BY ListPrice DESC;
GO

-- Q3 Author: Wamalwa Trophily Misiko
-- Q3: I am interested in net revenue. I define net revenue as
--     list price less standard cost. Which three road bikes
--     generate the least net revenue per unit sold?
-- A3: Calculate net revenue per unit and return the three
--     road bikes with the lowest net revenue.

SELECT TOP 3
       p.ProductID,
       p.Name,
       p.ListPrice,
       p.StandardCost,
       (p.ListPrice - p.StandardCost) AS NetRevenuePerUnit
FROM Production.Product p
INNER JOIN Production.ProductSubcategory ps
       ON p.ProductSubcategoryID = ps.ProductSubcategoryID
WHERE ps.Name = 'Road Bikes'
ORDER BY NetRevenuePerUnit ASC;
GO

-- Q4 Author: Wamalwa Trophily Misiko
-- Q4: Which product subcategories have the highest average list price?Please show the subcategory 
-- name and the average list price, sorted from highest to lowest.
-- A4: Calculate average list price by subcategory and sort from
--     highest to lowest.

SELECT
       ps.Name AS ProductSubcategory,
       AVG(p.ListPrice) AS AverageListPrice
FROM Production.Product p
INNER JOIN Production.ProductSubcategory ps
       ON p.ProductSubcategoryID = ps.ProductSubcategoryID
GROUP BY ps.Name
ORDER BY AverageListPrice DESC;
GO

-- Q5 Author: Junior Enama Benyomo
-- Q5: Our regional manager for the European market wants to review order patterns 
-- before the next budgeting cycle. Specifically, she would like to see, for each 
-- quarter of 2013, the total number of orders and total sales revenue generated by 
-- customers located in France and Germany.
-- A5: Summarize quarterly order counts and revenue for customers
--     located in France and Germany.

SELECT
       DATEPART(QUARTER, soh.OrderDate) AS QuarterNumber,
       cr.Name AS Country,
       COUNT(DISTINCT soh.SalesOrderID) AS TotalOrders,
       SUM(soh.TotalDue) AS TotalRevenue
FROM Sales.SalesOrderHeader soh
INNER JOIN Sales.SalesTerritory st
       ON soh.TerritoryID = st.TerritoryID
INNER JOIN Person.CountryRegion cr
       ON st.CountryRegionCode = cr.CountryRegionCode
WHERE YEAR(soh.OrderDate) = 2013
  AND cr.Name IN ('France', 'Germany')
GROUP BY
       DATEPART(QUARTER, soh.OrderDate),
       cr.Name
ORDER BY
       cr.Name,
       QuarterNumber;
GO

-- Q6 Author: Junior Enama Benyomo
-- Q6: Our warehouse team has noticed that several products seem to be selling 
-- faster than expected during the holiday season. To help plan next year's inventory, 
-- I need to know which five products had the highest total quantity ordered during 
-- November and December of 2013, along with their safety stock levels.
-- A6: Identify the top five products by quantity sold during the
--     holiday season and display their safety stock levels.

SELECT TOP 5
       p.ProductID,
       p.Name,
       p.SafetyStockLevel,
       SUM(sod.OrderQty) AS TotalQuantityOrdered
FROM Sales.SalesOrderHeader soh
INNER JOIN Sales.SalesOrderDetail sod
       ON soh.SalesOrderID = sod.SalesOrderID
INNER JOIN Production.Product p
       ON sod.ProductID = p.ProductID
WHERE YEAR(soh.OrderDate) = 2013
  AND MONTH(soh.OrderDate) IN (11, 12)
GROUP BY
       p.ProductID,
       p.Name,
       p.SafetyStockLevel
ORDER BY TotalQuantityOrdered DESC;
GO

-- Q7 Author: King Brandan Mthimunye
-- Q7: Can you provide a list of all table names within the
--     AdventureWorks database that contain a column named BusinessEntityID?
-- A7: Query INFORMATION_SCHEMA.COLUMNS to find all tables containing
--     the BusinessEntityID column.

SELECT
       TABLE_SCHEMA,
       TABLE_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = 'BusinessEntityID'
ORDER BY
       TABLE_SCHEMA,
       TABLE_NAME;
GO

-- Q8 Author: King Brandan Mthimunye
-- Q8: Which system views in the INFORMATION_SCHEMA schema can I query
--     to display all columns and their data types for the
--     Sales.SalesOrderHeader table?
-- A8: Use INFORMATION_SCHEMA.COLUMNS to display column names,
--     data types, lengths, and nullability.

SELECT
       COLUMN_NAME,
       DATA_TYPE,
       CHARACTER_MAXIMUM_LENGTH,
       IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'Sales'
  AND TABLE_NAME = 'SalesOrderHeader'
ORDER BY ORDINAL_POSITION;
GO
